# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(5, 2, 5, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.Log = QtWidgets.QWidget()
        self.Log.setObjectName("Log")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Log)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textLog = QtWidgets.QTextBrowser(self.Log)
        self.textLog.setObjectName("textLog")
        self.gridLayout_3.addWidget(self.textLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Log, "")
        self.Terminal = QtWidgets.QWidget()
        self.Terminal.setObjectName("Terminal")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Terminal)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textTerminal = QtWidgets.QTextBrowser(self.Terminal)
        self.textTerminal.setObjectName("textTerminal")
        self.gridLayout_4.addWidget(self.textTerminal, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Terminal, "")
        self.Curve = QtWidgets.QWidget()
        self.Curve.setObjectName("Curve")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Curve)
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QChartView(self.Curve)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.Curve)
        self.widget_2.setObjectName("widget_2")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 10, 951, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(0, 15)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.widget_3 = QtWidgets.QWidget(self.Curve)
        self.widget_3.setObjectName("widget_3")
        self.cbxCH1 = QtWidgets.QCheckBox(self.widget_3)
        self.cbxCH1.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.cbxCH1.setObjectName("cbxCH1")
        self.labCH1 = QtWidgets.QLabel(self.widget_3)
        self.labCH1.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.labCH1.setObjectName("labCH1")
        self.cbxCH2 = QtWidgets.QCheckBox(self.widget_3)
        self.cbxCH2.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.cbxCH2.setObjectName("cbxCH2")
        self.labCH2 = QtWidgets.QLabel(self.widget_3)
        self.labCH2.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.labCH2.setObjectName("labCH2")
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout.setStretch(0, 12)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 30)
        self.tabWidget.addTab(self.Curve, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_plot = QtWidgets.QWidget(self.tab)
        self.widget_plot.setObjectName("widget_plot")
        self.gridLayout_7.addWidget(self.widget_plot, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 4, 1, 1)
        self.textSend = QtWidgets.QTextEdit(self.groupBox_2)
        self.textSend.setObjectName("textSend")
        self.gridLayout_5.addWidget(self.textSend, 0, 1, 1, 1)
        self.btnSend = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnSend.setFont(font)
        self.btnSend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSend.setStyleSheet("color: rgb(85, 170, 255);")
        self.btnSend.setAutoDefault(False)
        self.btnSend.setDefault(False)
        self.btnSend.setFlat(True)
        self.btnSend.setObjectName("btnSend")
        self.gridLayout_5.addWidget(self.btnSend, 0, 2, 1, 1)
        self.btnClean = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnClean.setFont(font)
        self.btnClean.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClean.setStyleSheet("color: rgb(85, 170, 255);")
        self.btnClean.setAutoDefault(False)
        self.btnClean.setDefault(False)
        self.btnClean.setFlat(True)
        self.btnClean.setObjectName("btnClean")
        self.gridLayout_5.addWidget(self.btnClean, 0, 3, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 40)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(1, 80)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionlianjie = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/ico/开关-关.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionlianjie.setIcon(icon)
        self.actionlianjie.setObjectName("actionlianjie")
        self.actionduankai = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../.designer/backup/ico/开关-开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionduankai.setIcon(icon1)
        self.actionduankai.setObjectName("actionduankai")
        self.actiontuichu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../.designer/backup/ico/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontuichu.setIcon(icon2)
        self.actiontuichu.setObjectName("actiontuichu")
        self.actionqingchu = QtWidgets.QAction(MainWindow)
        self.actionqingchu.setObjectName("actionqingchu")
        self.actionshowLog = QtWidgets.QAction(MainWindow)
        self.actionshowLog.setObjectName("actionshowLog")
        self.menu.addAction(self.actionlianjie)
        self.menu.addAction(self.actionduankai)
        self.menu.addAction(self.actiontuichu)
        self.menu_2.addAction(self.actionqingchu)
        self.menu_2.addAction(self.actionshowLog)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RTT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log), _translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Terminal), _translate("MainWindow", "Terminal"))
        self.cbxCH1.setText(_translate("MainWindow", "CH1"))
        self.labCH1.setText(_translate("MainWindow", "0"))
        self.cbxCH2.setText(_translate("MainWindow", "CH2"))
        self.labCH2.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Curve), _translate("MainWindow", "Curve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Plot"))
        self.btnSend.setText(_translate("MainWindow", "发送"))
        self.btnClean.setText(_translate("MainWindow", "清除"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "窗口"))
        self.actionlianjie.setText(_translate("MainWindow", "连接"))
        self.actionduankai.setText(_translate("MainWindow", "断开"))
        self.actiontuichu.setText(_translate("MainWindow", "退出"))
        self.actionqingchu.setText(_translate("MainWindow", "清除窗口"))
        self.actionshowLog.setText(_translate("MainWindow", "显示Log"))
from PyQt5.QtChart import QChartView
